version: "3.8"

services:
  polybot-dev:
    image: "${IMG_NAME}"
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - /home/ubuntu/polybot-dev.crt:/app/polybot-dev.crt
#    depends_on:
#      - yolo

