name: Docker Scout PR Scan

on:
  pull_request:
    branches:
      - main

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/polybot-scout:${{ github.sha }} .

    - name: Run Docker Scout scan
      uses: docker/scout-action@v1
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/polybot-scout:${{ github.sha }}
        only-severities: critical,high
        exit-code: 1                    # ❌ Fail the job if CRITICAL or HIGH vulnerabilities
        summary: true                   # ✅ Show results in GitHub Actions summary
        write-comment: true            # ✅ Post a comment on the PR
        github-token: ${{ secrets.GITHUB_TOKEN }}
